# Verify Mitsurunner hardware: 
# Shows IDs of connected Dallas temperature sensors in Esphome window after succefull run, write these down.
# Tests relay, switches on and off: 1sec on, 10sec off

esphome:
  name: mitsurunner-hw-check  
# HW-platform
  platform: esp8266
  board: d1_mini

wifi:
# EDIT HERE: SSID and PASSWORD: Set your WiFi name and password
  ssid: "ssid"
  password: "pw"

  manual_ip:
# Mitsurunner's IP address
    static_ip: 192.168.1.100
    subnet: 255.255.255.0
    gateway: 192.168.1.1

# Logs on
logger:

# EDIT HERE: PASSWORD: Choose and fill in secure OtA update password
ota:
  - platform: esphome
    password: "0tapazzzwordz"

# Dallas PIN, change PIN if needed
one_wire:
  - platform: gpio
    pin: D5
    id: dallas1

# Relay PIN
switch:
  - platform: gpio
    pin: D1
    name: "rele"
    id: gpio_rele

light:
  - platform: status_led
    pin:
      number: D4
      inverted: True
    name: "Status led"

# Switch relay on and off
interval:
  - interval: 10s
    then:
      - switch.turn_on: gpio_rele
      - delay: 0.5s
      - switch.turn_off: gpio_rele
